# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(default='default location'),
        ),
    ]
